export const GET_ALL_CONTRATOS_ALMACEN = "GET_ALL_CONTRATOS_ALMACEN";
export const GET_ALL_SEDES_ALMACEN = "GET_ALL_SEDES_ALMACEN";
export const GET_ALL_MOVIMIENTOS_BY_SEDE = "GET_ALL_MOVIMIENTOS_BY_SEDE";
export const GET_ALL_NAVES_ALMACEN = "GET_ALL_NAVES_ALMACEN";
export const GET_ALL_ZONAS_ALMACEN = "GET_ALL_ZONAS_ALMACEN";
export const GET_UBICACION_BY_PARAMS = "GET_UBICACION_BY_PARAMS";